HabTalksMVC/Controllers/RegisterController.cs
using Core;
using HabTalksMVC.Models;
using HabTalksMVC.Utilities;
using log4net;
using Razorpay.Api;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Configuration;
using System.Web.Mvc;

namespace HabTalksMVC.Controllers
{
    public class RegisterController : Controller
    {
        public ILog log = log4net.LogManager.GetLogger(typeof(RegisterController));

        // GET: Register
        public ActionResult Index()
        {
            MainPageModel main = new MainPageModel();
            using (var context = new HabTalksEntities())
            {
                main.painarea = context.PainAreas.ToList();
            }
            return View(main);
        }

        [HttpPost]
        public ActionResult Schedule(MainPageModel booking)
        {
            bool isError = false;
            bool isImageSave = false;
            string FileName = string.Empty;

            Appointment Newappointment = new Appointment();
            var payment = new PaymentModel();
            try
            {
                var ISTCurrentDateTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("India Standard Time"));
                log.Warn(ISTCurrentDateTime);

                TimeSpan CurrentTimeSpan = ISTCurrentDateTime.TimeOfDay;

                string strAppointmentIntervalInMinutes = WebConfigurationManager.AppSettings["AppointmentInterval"];
                int AppointmentIntervalInMinutes = Convert.ToInt32(strAppointmentIntervalInMinutes);

                if (ModelState.IsValid)
                {
                    DateTime timespan = DateTime.Parse(booking.Time);  //gives us a DateTime object
                    TimeSpan SelectedTime = timespan.TimeOfDay;  //returns a TimeSpan from the Time portion

                    DateTime SelectedAppointmentDate = Convert.ToDateTime(booking.AppointmentDate);

                    // first compare date
                    if (ISTCurrentDateTime.Date == SelectedAppointmentDate.Date)
                    {
                        // Get Difference between times
                        TimeSpan difference = SelectedTime.Subtract(CurrentTimeSpan);

                        if (difference.TotalMinutes <= AppointmentIntervalInMinutes)
                        {
                            ViewBag.ErrorMessage = "Can not book appointment from current time upto 3 hours, please choose different time slot";
                            return View("Index", booking);
                        }
                    }

                    // check that 2 appointment is book or not if not book then proceed otherwise give a message
                    using (var context = new HabTalksEntities())
                    {
                        int TotalAppointmentBooked = context.ClientAppointments.Where(x => 
                        DbFunctions.TruncateTime(x.AppointmentDate) == DbFunctions.TruncateTime(SelectedAppointmentDate) &&
                        x.Time == SelectedTime).Count();

                        if (TotalAppointmentBooked >= 2)
                        {
                            ViewBag.ErrorMessage = "All available bookings for time slot are already done, please choose different time slot";
                            return View("Index", booking);
                        }
                    }

                    if (booking.painarea.Where(x => x.IsSelected == true).Count() == 0)
                    {
                        ModelState.AddModelError("PainAreaError", "Select atleast one pain area");
                        return View("Index", booking);
                    }
                    if (booking.painarea.Where(x => x.IsSelected == true).Count() > 1)
                    {
                        ModelState.AddModelError("PainAreaError", "Select only one pain area");
                        return View("Index", booking);
                    }

                    if (booking.ReportFile != null && booking.ReportFile.ContentLength > 0)
                    {
                        try
                        {
                            string FileExtension = Path.GetExtension(booking.ReportFile.FileName).ToLower();

                            if (FileExtension == ".png" || FileExtension == ".jpg" || FileExtension == ".jpeg" || FileExtension == ".pdf")
                            {
                                if (booking.ReportFile.ContentLength > 3000000)
                                {
                                    ModelState.AddModelError("ReportFileError", "Allow file only upto 3MB");
                                    ViewBag.ErrorMessage = "File size limit exceed";
                                    return View("Index", booking);
                                }
                                else
                                {
                                    if (!Directory.Exists(Server.MapPath("~/" + GlobalClass.UploadReportImage)))
                                        Directory.CreateDirectory(Server.MapPath("~/" + GlobalClass.UploadReportImage));

                                    Guid g = Guid.NewGuid();
                                    FileName = g.ToString() + Path.GetExtension(booking.ReportFile.FileName);

                                    string FullPath = Path.Combine(Server.MapPath("~/" + GlobalClass.UploadReportImage), FileName);
                                    booking.ReportFile.SaveAs(FullPath);
                                    isImageSave = true;
                                }
                            }
                            else
                            {
                                ModelState.AddModelError("ReportFileError", "Upload only png, jpg, jpeg or pdf file");
                                ViewBag.ErrorMessage = "Please upload valid report file";
                                return View("Index", booking);
                            }
                        }
                        catch (Exception ex)
                        {
                            isImageSave = false;
                        }
                    }

                    using (var context = new HabTalksEntities())
                    {
                        using (var dbContextTransaction = context.Database.BeginTransaction())
                        {
                            try
                            {
                                var NewBooking = new ClientBooking()
                                {
                                    Name = booking.ClientBookingModel.Name,
                                    DOB = Convert.ToDateTime(booking.ClientBookingModel.DOB),
                                    Gender = booking.ClientBookingModel.Gender,
                                    Mobile = booking.ClientBookingModel.CountryCode + booking.ClientBookingModel.Mobile,
                                    Email = booking.ClientBookingModel.Email,
                                    Weight = booking.ClientBookingModel.Weight,
                                    Height = booking.ClientBookingModel.Height,
                                    ActivityLevel = booking.ClientBookingModel.ActivityLevel,
                                    Profession = booking.ClientBookingModel.Profession,
                                    Consent = true, //booking.ClientBookingModel.Consent,

                                    WeightMeasure = booking.ClientBookingModel.WeightMeasure,
                                    HeightMeasure = booking.ClientBookingModel.HeightMeasure
                                };
                                context.ClientBookings.Add(NewBooking);
                                context.SaveChanges();

                                var LastId = NewBooking.Id;

                                payment.ClientId = LastId;

                                var newApointment = new ClientAppointment()
                                {
                                    AppointmentDate = SelectedAppointmentDate,
                                    Time = SelectedTime,                                    
                                    ClientId = LastId
                                };
                                context.ClientAppointments.Add(newApointment);
                                context.SaveChanges();

                                Newappointment.ClientId = LastId;

                                foreach (var item in booking.painarea)
                                {
                                    var clientpain = new ClientPainArea
                                    {
                                        ClientId = LastId,
                                        PainId = item.Id
                                    };
                                    if (item.IsSelected)
                                    {
                                        context.ClientPainAreas.Add(clientpain);
                                    }
                                }

                                context.SaveChanges();

                                //Save image if not empty
                                if (!string.IsNullOrEmpty(FileName) && isImageSave == true)
                                {
                                    var clientReport = new ClientReport()
                                    {
                                        ClientId = LastId,
                                        ReportName = "",
                                        ReportType = "",
                                        Report = FileName
                                    };
                                    context.ClientReports.Add(clientReport);
                                    context.SaveChanges();
                                }
                                dbContextTransaction.Commit();

HabTalksMVC/Views/Shared/Scheduler.cshtml
@model HabTalksMVC.Models.Appointment
    @{
        ViewBag.Title = "Scheduler";
    }
    @using (Html.BeginForm("SaveAppointment", "Register", FormMethod.Post))
    {
        <div class="well">
            <div class="form-group row">
                <label for="inputDOB" class="col-sm-3 col-form-label">Select Date</label>
                <div class="col-sm-5">
                    <div class='input-group' id='datetimepickerDate'>
                        @Html.TextBoxFor(m => m.appointment.AppointmentDate, new { @class = "form-control", @placeholder = "Appointment" })
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
                <div class="col-sm-4">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputDOB" class="col-sm-3 col-form-label">Time</label>
                <div class="col-sm-5">
                    <div class='input-group' id='datetimepickerTime'>
                        @Html.TextBoxFor(m => m.appointment.Time.TimeOfDay, new { @class = "form-control", @placeholder = "Time" })
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                </div>
                <div class="col-sm-4">
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-2"></div>
            <div class="col-sm-10 text-right">
                <input type="submit" id="BtnAppointment" class="btn btn-primary" value="Schedule" />
            </div>
        </div>
    }

HabTalksMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Care well provide a versatile service to your dear one.Get better and faster service at your door step. Clinical support to senior citizen and post-surgical patient">
    <meta name="keywords" content="physiotherapy Habtalks service,nursing service,personal care, senior citizen care, Habtalks service, elderly care">
    <title>@ViewBag.Title Habtalks</title>

    @Styles.Render("~/bundles/css")
    @RenderSection("styles", false)
    <style type="text/css">
        .error {
            color: red;
        }
    </style>

    <!-- Template Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700,300" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400italic" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="~/Content/images/favicon.png" type="image/x-icon">
</head>
<body class="animsition">
    @*<div class="collapse" id="searcharea">
            <div class="well-default">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Go!</button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@
    <!-- /.search area -->
    <div class="header">
        <!-- header -->
        <div class="container">
            <div class="row">
                <div class="col-xs-9 col-sm-4 col-md-4 header-logo">
                    <a href="/Home/Index" title="LOGO"><img src="~/Content/images/logo.png" alt=""></a>
                </div>
                <div class="col-xs-3 col-sm-8 col-md-8 header-text">
                    <span class="text-email"><a href="mailto:contact@habtalks.com">contact@habtalks.com</a></span>
                    @*<span class="search">
                            <a class="" role="button" data-toggle="collapse" href="#searcharea" aria-expanded="false">
                                <i class="fa fa-search"></i>
                            </a>
                        </span>*@
                </div>
            </div>
        </div>
    </div>
    <!-- /.header -->
    <div class="navigation">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div id="navigation">
                        <ul>
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Story", "Story", "Home")</li>
                            <li>@Html.ActionLink("Services", "Service", "Home")</li>
                            <li>@Html.ActionLink("Register", "Index", "Register")</li>
                            <li>@Html.ActionLink("Testimonials", "Testimonials", "Home")</li>
                            <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>

                            @*<li class="active"><a href="index.html" title="Home" class="animsition-link">Home</a></li>
                                <li><a href="story.html" title="Story" class="animsition-link">Story</a></li>
                                <li><a href="testimonials.html" title="Testimonials" class="animsition-link">Testimonials</a></li>
                                <li><a href="contact-us.html" title="Contact Us" class="animsition-link">Contact Us</a></li>
                                <li><a href="register.html" title="Register" class="animsition-link">Register</a></li>*@
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div>
        @RenderBody()
    </div>
    <div class="section-default-bg section-space-40 cta-section">
        <div class="container">
            <div class="row">
                <div class="col-md-9 cta-title">
                    <!-- cta title -->
                    <h2 class="heading-title-white">Do you need a personal physiotherapist?</h2>
                </div>
                <!-- /.cta title -->
                <div class="col-md-3">
                    <a href="/Register" class="btn btn-secondary btn-block">Book an appointment</a>
                </div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-2 footer-widget">
                    <!-- footer widget -->
                    <h3 class="footer-widget-title">Quick links</h3>
                    <ul class="listnone arrow">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Story", "Story", "Home")</li>
                        <li>@Html.ActionLink("Services", "Service", "Home")</li>
                        <li>@Html.ActionLink("Register", "Index", "Register")</li>
                        <li>@Html.ActionLink("Testimonials", "Testimonials", "Home")</li>
                        <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>

                        @*<li><a href="#">Home</a></li>
                            <li><a href="story.html" class="animsition-link">Story</a></li>
                            <li><a href="testimonials.html" class="animsition-link">Testimonials</a></li>
                            <li><a href="contact-us.html" class="animsition-link">Contact Us</a></li>
                            <li><a href="register.html" class="animsition-link">Register</a></li>*@
                    </ul>
                </div>
                <!-- /.footer widget -->
                <div class="col-md-4 footer-widget">
                    <!-- footer widget -->
                    <h3 class="footer-widget-title">Contact us</h3>
                    <ul class="listnone">
                        @*<li>
                                245 North Spruce Street, Redwood
                                city, California 94061
                            </li>
                            <li> Phone : 413-658-5373</li>*@
                        <li>
                            Email :
                            <a href="mailto:contact@habtalks.com">contact@habtalks.com</a>
                        </li>
                        <li>
                            We are available 24 hours
                            7 days a week
                        </li>
                    </ul>
                    <div class="footer-widget footer-social-widget">
                        <h3 class="footer-widget-title">Follow us</h3>
                        <ul class="listnone">
                            <li>
                                <a href="https://www.facebook.com/Habtalks/" target="_blank">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/habtalks/" target="_blank">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            @*<li><a href="#"><i class="fa fa-twitter"></i></a></li>*@
                            @*<li><a href="#"><i class="fa fa-google-plus"></i></a></li>*@
                            @*<li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>*@
                            <li>
                                <a href="https://www.linkedin.com/company/35926037/admin/" target="_blank">
                                    <i class="fa fa-linkedin-square"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /.footer widget -->
                <div class="col-md-2 footer-widget">
                    <!-- footer widget -->
                    <h3 class="footer-widget-title">Quick links</h3>
                    <ul class="listnone arrow">
                        <li>@Html.ActionLink("Terms & Conditions", "TermsAndConditions", "Home")</li>
                        <li>@Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home")</li>
                        <li>@Html.ActionLink("Terms Of Use", "TermsOfUse", "Home")</li>
                    </ul>
                </div>
                <!-- /.footer widget -->
                <div class="col-md-4 footer-widget">
                    <!-- footer widget -->
                    <h3 class="footer-widget-title">Our Story</h3>
                    <p>
                        Habtalks, being the very first Telerehabilitation Startup in India,
                        set the balls rolling with the goal to reach out to every individual possible in exigency.
                        <br><a href="/Home/Story" class="btn-link animsition-link"> View More</a>
                    </p>
                </div>
                <!-- /.footer widget -->
            </div>
        </div>
    </div>

    <div class="tiny-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright-text">Copyright 2019 HabTalks. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- back to top icon -->
    <a href="#0" class="cd-top" title="Go to top">Top</a>

    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", false)
</body>
</html>

HabTalksMVC/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/images/Logo.png" type="image/gif" sizes="16x16">
    <title>@ViewBag.Title Habtalks</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/Common")

    <style type="text/css">
        .error {
            color: red;
        }
    </style>

</head>
<body id="top">
    <div class="wrapperHeading row1">
        <header id="header" class="hocHeading clear">
            <section>
                <div style="padding-top: 8px">
                    <a href="/Home/Index">
                        <img src="~/images/Logo.png" style="width: 80px; height: 80px; margin-left: 50px" />
                    </a>
                </div>
                <div>
                    <h1 id="logo"><a href="/Home/Index">HabTalks</a></h1>
                </div>
                <div style="padding-right: 50px">
                    <form class="clear" method="post" action="#">
                        <fieldset>
                            <input type="search" value="" placeholder="Search Here&hellip;">
                            <button class="fa fa-search" type="submit" title="Search"><em>Search</em></button>
                        </fieldset>
                    </form>
                </div>
            </section>
            <div>
                <nav id="mainav" style="width: 80%; margin-left: 120px; margin-right: 120px">
                    <ul class="clear">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Story", "Story", "Home")</li>
                        <li>@Html.ActionLink("Physiotherapy", "Physiotherapy", "Home")</li>
                        <li>@Html.ActionLink("Testimonials", "Testimonials", "Home")</li>
                        <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Register", "Index", "Register")</li>
                    </ul>
                </nav>
            </div>
        </header>
    </div>

    <div class="clear"></div>
    <!-- main body -->

    <div class="content">
        <div class="group">
            <div class="one_quarter first">&nbsp;</div>
            <div class="two_quarter">
                @RenderBody()
            </div>
            <div class="one_quarter">&nbsp;</div>
        </div>
    </div>
    <!-- / main body -->
    <div class="clear"></div>
    <div class="wrapper row3">&nbsp;</div>
    <div class="wrapper coloured">
        <article>&nbsp;</article>
    </div>
    <div class="wrapper row4">
        <footer id="footer" class="hoc clear">
            <div class="one_third first" style="padding-left: 20px">
                <h6 class="heading">Quick Links</h6>
                <ul class="nospace linklist">
                    <li>@Html.ActionLink("Terms & Conditions", "TermsAndConditions", "Home")</li>
                    <li>@Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home")</li>
                    <li>@Html.ActionLink("Terms Of Use", "TermsOfUse", "Home")</li>
                </ul>
            </div>
            <div class="one_third">
                <h6 class="heading">Contact Us</h6>
                <ul class="nospace btmspace-30 linklist contact">

                    <li><i class="fa fa-envelope-o"></i>support@habtalks.com</li>
                </ul>
                <ul class="faico clear">
                    <li>&nbsp;</li>
                    <li>&nbsp;</li>
                    <li><a class="faicon-facebook" target="_blank" href="https://www.facebook.com/habtalks-102370854754068/"><i class="fa fa-facebook"></i></a></li>
                    <li><a class="faicon-instagram" target="_blank" href="https://instagram.com/habtalks?igshid=fkpf7ate63h2"><i class="fa fa-instagram"></i></a></li>
                </ul>
            </div>

            <div class="one_third">
                <h6 class="heading">Story</h6>
                <article class="btmspace-30">

                    <p>
                        HabTalks started as a dream to transform the Rehabilitation domain in India
                        and make it more accessible. It is the first of its kind Telerehabilitation&hellip;
                        @Html.ActionLink("more", "Story", "Home")
                    </p>
                </article>
            </div>
        </footer>
    </div>
    <div class="wrapper row5">
        <div id="copyright" class="hoc clear">
            <p class="fl_left">Copyright &copy; 2019 - All Rights Reserved - <a href="http://www.HabTalks.com">HabTalks</a></p>
        </div>
    </div>
    <a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>
    <!-- JAVASCRIPTS -->
    <script src="~/Scripts/moment.min.js"></script>
    <script src="/Scripts/bootstrap-datetimepicker.min.js"></script>
    <link href="/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script>
        $(document).ready(function () {
            $('#datetimepicker1').datetimepicker({
                //format: 'L',
                maxDate: new Date(),
                useCurrent: false,
                format: 'DD/MM/YYYY'
            });
            $('#datetimepickerDate').datetimepicker({
                //format: 'L',
                minDate: new Date(),
                format: 'DD/MM/YYYY'
            });
            $('#datetimepickerTime').datetimepicker({
                format: 'LT',
                disabledHours: [0, 1, 2, 3, 4, 5, 6, 7, 8, 19, 20, 21, 22, 23, 24],
                enabledHours: [9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
            });
        });
    </script>
</body>
</html>